package com.wechseltech.chartlibrary;

public enum  Type {

	PIE,DOUGHNUT,SPIDERWEB,BUBBLE,SCATTERPLOT,STACKEDBARHORIZONTAL,STACKEDBAR,STACKEDBARNEW,MULTIPLESERIESBARCHART,RANGE,LINE,AREA
	,NEGATIVESTACKBARCHART,POLAR,GAUGE,WINDROSE,MULTIPLESERIESBARCHARTNEW,LINECHARTXML,LINECHART;
}
